// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: geofence.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GeoFenceServiceClient is the client API for GeoFenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeoFenceServiceClient interface {
	// Add polygons to the geo-fence for tracking.
	AddPolygons(ctx context.Context, in *AddPolygonsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// A server-side streaming RPC for sending filtered location data.
	StreamFilteredLocations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (GeoFenceService_StreamFilteredLocationsClient, error)
}

type geoFenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoFenceServiceClient(cc grpc.ClientConnInterface) GeoFenceServiceClient {
	return &geoFenceServiceClient{cc}
}

func (c *geoFenceServiceClient) AddPolygons(ctx context.Context, in *AddPolygonsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/smartify.geofence.GeoFenceService/AddPolygons", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geoFenceServiceClient) StreamFilteredLocations(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (GeoFenceService_StreamFilteredLocationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &GeoFenceService_ServiceDesc.Streams[0], "/smartify.geofence.GeoFenceService/StreamFilteredLocations", opts...)
	if err != nil {
		return nil, err
	}
	x := &geoFenceServiceStreamFilteredLocationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GeoFenceService_StreamFilteredLocationsClient interface {
	Recv() (*FilteredLocations, error)
	grpc.ClientStream
}

type geoFenceServiceStreamFilteredLocationsClient struct {
	grpc.ClientStream
}

func (x *geoFenceServiceStreamFilteredLocationsClient) Recv() (*FilteredLocations, error) {
	m := new(FilteredLocations)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GeoFenceServiceServer is the server API for GeoFenceService service.
// All implementations must embed UnimplementedGeoFenceServiceServer
// for forward compatibility
type GeoFenceServiceServer interface {
	// Add polygons to the geo-fence for tracking.
	AddPolygons(context.Context, *AddPolygonsRequest) (*emptypb.Empty, error)
	// A server-side streaming RPC for sending filtered location data.
	StreamFilteredLocations(*emptypb.Empty, GeoFenceService_StreamFilteredLocationsServer) error
	mustEmbedUnimplementedGeoFenceServiceServer()
}

// UnimplementedGeoFenceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeoFenceServiceServer struct {
}

func (UnimplementedGeoFenceServiceServer) AddPolygons(context.Context, *AddPolygonsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPolygons not implemented")
}
func (UnimplementedGeoFenceServiceServer) StreamFilteredLocations(*emptypb.Empty, GeoFenceService_StreamFilteredLocationsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamFilteredLocations not implemented")
}
func (UnimplementedGeoFenceServiceServer) mustEmbedUnimplementedGeoFenceServiceServer() {}

// UnsafeGeoFenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoFenceServiceServer will
// result in compilation errors.
type UnsafeGeoFenceServiceServer interface {
	mustEmbedUnimplementedGeoFenceServiceServer()
}

func RegisterGeoFenceServiceServer(s grpc.ServiceRegistrar, srv GeoFenceServiceServer) {
	s.RegisterService(&GeoFenceService_ServiceDesc, srv)
}

func _GeoFenceService_AddPolygons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPolygonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoFenceServiceServer).AddPolygons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smartify.geofence.GeoFenceService/AddPolygons",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoFenceServiceServer).AddPolygons(ctx, req.(*AddPolygonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeoFenceService_StreamFilteredLocations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GeoFenceServiceServer).StreamFilteredLocations(m, &geoFenceServiceStreamFilteredLocationsServer{stream})
}

type GeoFenceService_StreamFilteredLocationsServer interface {
	Send(*FilteredLocations) error
	grpc.ServerStream
}

type geoFenceServiceStreamFilteredLocationsServer struct {
	grpc.ServerStream
}

func (x *geoFenceServiceStreamFilteredLocationsServer) Send(m *FilteredLocations) error {
	return x.ServerStream.SendMsg(m)
}

// GeoFenceService_ServiceDesc is the grpc.ServiceDesc for GeoFenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeoFenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "smartify.geofence.GeoFenceService",
	HandlerType: (*GeoFenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPolygons",
			Handler:    _GeoFenceService_AddPolygons_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamFilteredLocations",
			Handler:       _GeoFenceService_StreamFilteredLocations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "geofence.proto",
}
